### PR TITLE
Implement a query string assembler function

### PR DESCRIPTION
**Pull request by gshel**
Hey Brad!

This PR aims to address issue #15 

I've identified a number of Harvest methods that might benefit from the function I've implemented, which is called `assemble_query_string` -- `ctrl+f` "# TODO: ISSUE 15"

The purpose of this function is to replace the url formatting that we see repeated throughout the Harvest methods with abstracted, reusable code. I felt that it would be cleaner than adding in a bunch of nested if statements to convert bool kwargs to lowercase strings.

Let me know what you think!

### CODE REVIEW

**Comment by gshel** [comment]
@bradbase I've also included a throwaway file called `[test.py](https://github.com/bradbase/python-harvest_apiv2/pull/19/commits/6f933c4a60ba3face49cb10a874326e7adc9783c)` so that you can play with the new function in isolation and make sure that it works for use cases that you can come up with.

**Comment by bradbase** [comment]
Hi @gshel Thanks for the PR! :smile:

I like the idea of assemble_query_string(), certainly saves a bunch of copy+paste.

I seem to recall an experience where the defaults, although heavily documented in the Harvest API doco, were required to be present in the URL for the request to be successful. In particular this is in respect to the page and per_page parameters.

I have written a test for assemble_query_string() which has calmed coveralls and am propagating assemble_query_string() throughout the Harvest object but I think it might be prudent for us to add a check to ensure page and per_page keys are being defined.

**Comment by gshel** [comment]
By the way, @bradbase, the docstrings I used are for Sphinx! Would that be something you're interested in? I can open a new PR to implement it :)

**Comment by bradbase** [comment]
Sphinx doco would be incredible.

Anything to make this library more approachable is highly valuable and "actual doco" is key for that.

There's a lot of doc strings to create :smile:

Please start a PR for it.

**Pull request merged**
